import {Card} from "./models/Card.tsx";

export const cards: Card[] = [
  {name: "fh-at-all-costs"},
  {name: "fh-combined-effort"},
  {name: "fh-deflecting-maneuver"},
  {name: "fh-javelin"},
  {name: "fh-pincer-movement"},
  {name: "fh-rallying-cry"},
  {name: "fh-regroup"},
  {name: "fh-set-for-the-charge"},
  {name: "fh-tip-of-the-spear"},
  {name: "fh-unbreakable-wall"},
  {name: "fh-driving-inspiration"},
  {name: "fh-incendiary-throw"},
  {name: "fh-resolved-courage"},
  {name: "fh-meat-grinder"},
  {name: "fh-pinning-charge"},
  {name: "fh-head-of-the-hammer"},
  {name: "fh-let-them-come"},
  {name: "fh-air-support"},
  {name: "fh-boldening-blow"},
  {name: "fh-explosive-epicenter"},
  {name: "fh-hold-the-line"},
  {name: "fh-barricade"},
  {name: "fh-bolstering-shout"},
  {name: "fh-lead-from-afar"},
  {name: "fh-tri-thrust"},
  {name: "fh-sweeping-aid"},
  {name: "fh-taunting-howl"},
  {name: "fh-hail-of-spears"},
  {name: "fh-take-no-prisoners"},
]
